name: Publish docker image

on:
    repository_dispatch:
      types: [pip-published]

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.1.0 # Optional fallback tag to use when no tag can be found
      - name: build and push
        run: |
          IMAGE_TAG=tsladecek/ksux:${{ steps.previoustag.outputs.tag }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
