name: Upload Python Package

on:
    release:
      types: [published]

jobs:
  pip-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 0.1.0 # Optional fallback tag to use when no tag can be found
    - name: Update Version
      run: |
        VERSION=${{ steps.previoustag.outputs.tag }}
        echo $VERSION
        sed -i "s/0.0.1/$VERSION/g" pyproject.toml
        sed -i "s/VERSION/$VERSION/g" src/ksux/__init__.py
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
  docker-publish:
    runs-on: ubuntu-latest
    needs: pip-publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.1.0
      - name: sleep because pypi takes time
        run: sleep 20
      - name: build and push
        run: |
          IMAGE_TAG=tsladecek/ksux:${{ steps.previoustag.outputs.tag }}
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u tsladecek --password-stdin
          docker build -t $IMAGE_TAG --build-arg VERSION=${{ steps.previoustag.outputs.tag }} .
          docker push $IMAGE_TAG